// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: favourites.sql

package database

import (
	"context"
	"database/sql"
)

const favouriteRecipe = `-- name: FavouriteRecipe :exec
INSERT INTO favourites (user_id, recipe_id)
VALUES ($1, $2)
ON CONFLICT (user_id, recipe_id) DO NOTHING
`

type FavouriteRecipeParams struct {
	UserID   sql.NullInt32
	RecipeID sql.NullInt32
}

func (q *Queries) FavouriteRecipe(ctx context.Context, arg FavouriteRecipeParams) error {
	_, err := q.db.ExecContext(ctx, favouriteRecipe, arg.UserID, arg.RecipeID)
	return err
}

const unfavouriteRecipe = `-- name: UnfavouriteRecipe :exec
DELETE FROM favourites
WHERE user_id = $1 AND recipe_id = $2
`

type UnfavouriteRecipeParams struct {
	UserID   sql.NullInt32
	RecipeID sql.NullInt32
}

func (q *Queries) UnfavouriteRecipe(ctx context.Context, arg UnfavouriteRecipeParams) error {
	_, err := q.db.ExecContext(ctx, unfavouriteRecipe, arg.UserID, arg.RecipeID)
	return err
}
