// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"
)

type Favourite struct {
	ID       int32
	UserID   sql.NullInt32
	RecipeID sql.NullInt32
}

type Like struct {
	ID       int32
	UserID   sql.NullInt32
	RecipeID sql.NullInt32
}

type Recipe struct {
	ID           int32
	UserID       sql.NullInt32
	Title        string
	Description  sql.NullString
	Tags         []string
	Ingredients  []string
	Instructions []string
	TotalTime    sql.NullInt32
	Difficulty   sql.NullString
	Servings     sql.NullInt32
	PhotoUrl     sql.NullString
	CreatedAt    sql.NullTime
}

type User struct {
	ID         int32
	Name       string
	Email      string
	Password   string
	ProfileUrl sql.NullString
	CreatedAt  time.Time
}
