-- +goose Up
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    profile_url TEXT created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
);

-- +goose Down
DROP TABLE IF EXISTS users;
